#include <iostream>
#include <string>

using namespace std;

int main()
{
    cout << "|_________________________________________________________________________________________________________________________________________________________________________________________________________________|" << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;                                                                                                                                                                                                                 
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   |" << endl;
    cout << "                                                                                                                                                                                                                   |" << endl;
    cout << "                                                                                                                                                                                                                   |" << endl;
    cout << "                                                                                                                                                                                                                   |" << endl;
    cout << "                                                                                                                                                                                                                   |" << endl;
    cout << "                                                                                                                                                                                                                   |" << endl;
    cout << "                                                                                                                                                                                                                   |" << endl;
    cout << "                                                                                                                                                                                                                   |" << endl;
    cout << "                                                                                                                                                                                                                  |" << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   " << endl;
    cout << "                                                                                                                                                                                                                   |" << endl;
    cout << "                                                                                                                                                                                                                  |" << endl;
    cout << "                                                                                                                                                                                                                  |" << endl;
    cout << "                                                                                                                                                                                                                  |" << endl;
    cout << "                                                                                                                                                                                                                  |" << endl;
    cout << "|_________________________________________________________________________________________________________________________________________________________________________________________________________________|" << endl;

}